### ISSUE TITLE
500 internal error

### ISSUE THREAD

**Issue by ghost** [hazzardweb/ajax-comment-system-laravel-demo#1]
hi im getting 500 internal error when i post a comment

this is the error log when posting comment

http://pastebin.com/h53EycEG

is it because of "Maximum function nesting level of '100' reached, aborting!"

**Comment by cretueusebiu** [comment]
Do you have xdebug on ? See this http://stackoverflow.com/questions/17488505/php-error-maximum-function-nesting-level-of-100-reached-aborting
