### ISSUE TITLE
Hii sir

### ISSUE THREAD

**Issue by man9035206** [hazzardweb/ajax-comment-system-laravel-demo#3]
when ever i tried to composer install i'm getting error
[Symfony\Component\Debug\Exception\FatalErrorException]     
  Class 'Hazzard\Comments\CommentsServiceProvider' not found

how can i fix this
Thank you

**Comment by cretueusebiu** [comment]
Hi, this is only a demo Laravel app. If you want to use the comments you'll have to download the comment script from [here](https://codecanyon.net/item/ajax-comment-system-for-laravel/12660889).

**Comment by man9035206** [comment]
OK thank you very much sir
