### ISSUE TITLE
Installation Problem

### ISSUE THREAD

**Issue by evinkuraga** [hazzardweb/ajax-comment-system-laravel-demo#4]
Trying to install this package with composer gives:
[InvalidArgumentException]                                                                                                                                
  Could not find package hazzard/laravel-comments at any version for your minimum-stability (stable). Check the package spelling or your minimum-stability  

Command typed:
composer require hazzard/laravel-comments *@dev

**Comment by cretueusebiu** [comment]
Have you followed the [installation guide](http://docs.hazzardweb.com/laravel-comments/2.0) ?

**Comment by evinkuraga** [comment]
Yes I have. Here are the steps to retrace:

1.  git clone https://github.com/hazzardweb/laravel-comments-demo.git
2. cd /to/cloned/folder/
3. edited composer.json file with:
"repositories": [
    {
        "type": "path",
        "url": "./laravel-comments"
    }
]
4. composer require hazzard/laravel-comments *@dev
....
Didn't work., so tried 
composer require hazzard/laravel-comments

And composer update then run same command. No luck.

**Comment by evinkuraga** [comment]
Yes I have. Here are the steps to retrace:


1.

git clone https://github.com/hazzardweb/laravel-comments-demo.git

2. cd /to/cloned/folder/


3. edited composer.json file with:

"repositories": [
    {
        "type": "path",
        "url": "./laravel-comments"
    }
]

4. composer require hazzard/laravel-comments *@dev

....

Didn't work., so tried

composer require hazzard/laravel-comments


And composer update then run same command. No luck.

________________________________

**Comment by cretueusebiu** [comment]
Do you have the `laravel-comments` folder with the contents from CodeCanyon ? 

Please send me a message via CodeCanyon for support.
