### ISSUE TITLE
The Mix manifest does not exist. (View: /path/to/my/project/laravel-comments-demo/resources/views/home.blade.php)

### ISSUE THREAD

**Issue by gimtonic** [hazzardweb/ajax-comment-system-laravel-demo#6]
Hi! 
node v8.0.0
npm 5.0.0
yarn 1.5.1
nvm v8.0.0
ubuntu 16.04
php 7.1
laravel 5.5
Also don't work after 
php artisan vendor:publish --provider="Laravel\Horizon\HorizonServiceProvider"
What must I do?

**Comment by gimtonic** [comment]
yarn dev do also

**Comment by cretueusebiu** [comment]
Hi, please contact me via CodeCanyon with the error message that you get and maybe a link and access to the server and I'll take a look.

**Comment by gimtonic** [comment]
Why you need to communicate via CodeCanyon? It costs money? 
I need to do a test task(laravel blog with comments) to get a job)

**Comment by cretueusebiu** [comment]
This is just a demo Laravel application for the comment script that you bought from CodeCanyon. The support is provided from there.

**Comment by gimtonic** [comment]
Ok. Thank you very match)
